# Cleaning Data

Cleaning data is a big topic. Every data set might have its own issues whether that involves missing values, duplicated entries, data entry mistakes, etc. In this exercise, you'll do some data cleaning on the World Bank projects and World Bank indicators data sets. 

Currently, the projects data and the indicators data have different values for country names. Your task in this exercise is to clean both data sets so that they have consistent country names. This will allow you to join the two data sets together. Cleaning data, unfortunately, can be tedious and take a lot of your time as a data scientist.

Why might you want to join these data sets together? What if, for example, you wanted to run linear regression to try to predict project costs based on indicator data? Or you might want to analyze the types of projects that get approved versus the indicator data. For example, do countries with low rates of rural electrification have more rural themed projects?

# Part 1 - Explore the Data

Run the code cells below to import the data sets. The code cell will also output the unique country names in each data set.

In [3]:
import pandas as pd

# read in the population data and drop the final column
df_indicator = pd.read_csv('../data/population_data.csv', skiprows=4)
df_indicator.drop(['Unnamed: 62'], axis=1, inplace=True)

# read in the projects data set with all columns type string
df_projects = pd.read_csv('../data/projects_data.csv', dtype=str)
df_projects.drop(['Unnamed: 56'], axis=1, inplace=True)

In [4]:
df_indicator.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54211.0,55438.0,56225.0,56695.0,57032.0,57360.0,...,101353.0,101453.0,101669.0,102053.0,102577.0,103187.0,103795.0,104341.0,104822.0,105264.0
1,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8996351.0,9166764.0,9345868.0,9533954.0,9731361.0,9938414.0,...,27294031.0,28004331.0,28803167.0,29708599.0,30696958.0,31731688.0,32758020.0,33736494.0,34656032.0,35530081.0
2,Angola,AGO,"Population, total",SP.POP.TOTL,5643182.0,5753024.0,5866061.0,5980417.0,6093321.0,6203299.0,...,21759420.0,22549547.0,23369131.0,24218565.0,25096150.0,25998340.0,26920466.0,27859305.0,28813463.0,29784193.0
3,Albania,ALB,"Population, total",SP.POP.TOTL,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,...,2947314.0,2927519.0,2913021.0,2905195.0,2900401.0,2895092.0,2889104.0,2880703.0,2876101.0,2873457.0
4,Andorra,AND,"Population, total",SP.POP.TOTL,13411.0,14375.0,15370.0,16412.0,17469.0,18549.0,...,83861.0,84462.0,84449.0,83751.0,82431.0,80788.0,79223.0,78014.0,77281.0,76965.0

In [5]:
df_projects.head()

,id,regionname,countryname,prodline,lendinginstr,lendinginstrtype,envassesmentcategorycode,supplementprojectflg,productlinetype,projectstatusdisplay,...,mjtheme2name,mjtheme3name,mjtheme4name,mjtheme5name,location,GeoLocID,GeoLocName,Latitude,Longitude,Country
0,P162228,Other,World;World,RE,Investment Project Financing,IN,C,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P163962,Africa,Democratic Republic of the Congo;Democratic Re...,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,P167672,South Asia,People's Republic of Bangladesh;People's Repub...,PE,Investment Project Financing,IN,NaN,Y,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,P158768,South Asia,Islamic Republic of Afghanistan;Islamic Repu...,PE,Investment Project Financing,IN,A,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,P161364,Africa,Federal Republic of Nigeria;Federal Republic o...,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,NaN,0002327546!$!Ogun State!$!7!$!3.58333!$!NG;000...,0002327546;0002328925;0002565340;0002565343;00...,Ogun State;Niger State;Abia State;Edo;Kebbi St...,7;10;5.41667;6.5;11.5;8,3.58333;6;7.5;6;4;10.5,NG;NG;NG;NG;NG;NG

The next code cell outputs the unique country names and ISO abbreviations in the population indicator data set. You'll notice a few values that represent world regions such as 'East Asia & Pacific' and 'East Asia & Pacific (excluding high income)'.

In [6]:
df_indicator[['Country Name', 'Country Code']].drop_duplicates()

     Country Name Country Code
0           Aruba          ABW
1     Afghanistan          AFG
2          Angola          AGO
3         Albania          ALB
4         Andorra          AND
..            ...          ...
259        Kosovo          XKX
260   Yemen, Rep.          YEM
261  South Africa          ZAF
262        Zambia          ZMB
263      Zimbabwe          ZWE

[264 rows x 2 columns]

Run the next code cell to see the unique country names in the project data set. Notice that the projects data has two columns for country name. One is called 'countryname' and the other is called 'Country'. The 'Country' column only has NaN values.

Another thing of note: It would've been easier to join the two data sets together if the projects data had the [ISO country abbreviations](https://en.wikipedia.org/wiki/ISO_3166-1) like the indicator data has. Unfortunately, the projects data does not have the ISO country abbreviations. To join these two data sets together, you essentially have two choices:
* add a column of ISO 3 codes to the projects data set
* find the difference between the projects data country names and indicator data country names. Then clean the data so that they are the same.

Run the code cell below to see what the project countries look like:

In [7]:
df_projects['countryname'].unique()

array(['World;World',
       'Democratic Republic of the Congo;Democratic Republic of the Congo',
       "People's Republic of Bangladesh;People's Republic of Bangladesh",
       'Islamic  Republic of Afghanistan;Islamic  Republic of Afghanistan',
       'Federal Republic of Nigeria;Federal Republic of Nigeria',
       'Republic of Tunisia;Republic of Tunisia',
       'Lebanese Republic;Lebanese Republic',
       'Democratic Socialist Republic of Sri Lan;Democratic Socialist Republic of Sri Lan',
       'Nepal;Nepal', 'Kyrgyz Republic;Kyrgyz Republic',
       'Hashemite Kingdom of Jordan;Hashemite Kingdom of Jordan',
       'Republic of the Union of Myanmar;Republic of the Union of Myanmar',
       'Arab Republic of Egypt;Arab Republic of Egypt',
       'United Republic of Tanzania;United Republic of Tanzania',
       'Federal Democratic Republic of Ethiopia;Federal Democratic Republic of Ethiopia',
       'Burkina Faso;Burkina Faso',
       'Republic of Uzbekistan;Republic of Uzbekistan', 'Romania;Romania',
       'Republic of Ghana;Republic of Ghana',
       'Republic of Ecuador;Republic of Ecuador',
       'Socialist Republic of Vietnam;Socialist Republic of Vietnam',
       "People's Republic of China;People's Republic of China",
       'Republic of Senegal;Republic of Senegal', 'Grenada;Grenada',
       'Co-operative Republic of Guyana;Co-operative Republic of Guyana',
       'Central Africa;Central Africa',
       'Republic of Indonesia;Republic of Indonesia',
       'Republic of Kenya;Republic of Kenya',
       'Kingdom of Cambodia;Kingdom of Cambodia',
       'Republic of Angola;Republic of Angola',
       'Republic of India;Republic of India', 'Africa;Africa',
       'Republic of Zambia;Republic of Zambia',
       'Republic of Panama;Republic of Panama',
       'Kingdom of Tonga;Kingdom of Tonga',
       'Islamic Republic of Pakistan;Islamic Republic of Pakistan',
       'Republic of Niger;Republic of Niger',
       'Republic of Uganda;Republic of Uganda',
       'Republic of Madagascar;Republic of Madagascar',
       'Plurinational State of Bolivia;Plurinational State of Bolivia',
       'Kingdom of Morocco;Kingdom of Morocco',
       'Republic of Djibouti;Republic of Djibouti',
       'Somali Democratic Republic;Somali Democratic Republic',
       'Republic of Maldives;Republic of Maldives',
       'Central African Republic;Central African Republic',
       'Western Africa;Western Africa',
       'Republic of Cabo Verde;Republic of Cabo Verde',
       "Republic of Cote d'Ivoire;Republic of Cote d'Ivoire",
       'Montenegro;Montenegro', 'West Bank and Gaza;West Bank and Gaza',
       'Republic of Haiti;Republic of Haiti',
       'Republic of Guinea-Bissau;Republic of Guinea-Bissau',
       'Samoa;Samoa', 'Republic of Congo;Republic of Congo',
       'Federated States of Micronesia;Federated States of Micronesia',
       'Republic of the Marshall Islands;Republic of the Marshall Islands',
       'Republic of Rwanda;Republic of Rwanda',
       'Republic of Albania;Republic of Albania',
       'Republic of Burundi;Republic of Burundi',
       'Argentine Republic;Argentine Republic',
       'Pacific Islands;Pacific Islands',
       'Republic of Turkey;Republic of Turkey',
       'Democratic Republic of Sao Tome and Prin;Democratic Republic of Sao Tome and Prin',
       'Republic of The Gambia;Republic of The Gambia',
       "Lao People's Democratic Republic;Lao People's Democratic Republic",
       'Republic of Liberia;Republic of Liberia',
       'Republic of Benin;Republic of Benin',
       'Republic of Mozambique;Republic of Mozambique',
       'Kingdom of Bhutan;Kingdom of Bhutan',
       'Republic of Cameroon;Republic of Cameroon',
       'Republic of Chad;Republic of Chad',
       'Republic of Guinea;Republic of Guinea',
       'Republic of Yemen;Republic of Yemen',
       'Commonwealth of Dominica;Commonwealth of Dominica',
       'Republic of Palau;Republic of Palau',
       'Republic of Malawi;Republic of Malawi',
       'Republic of Serbia;Republic of Serbia',
       'Republic of Iraq;Republic of Iraq',
       'Republic of the Philippines;Republic of the Philippines',
       'Solomon Islands;Solomon Islands',
       'Republic of Fiji;Republic of Fiji',
       'United Mexican States;United Mexican States',
       'Republic of Colombia;Republic of Colombia',
       'Republic of Peru;Republic of Peru',
       'Republic of Mali;Republic of Mali',
       'Islamic Republic of Mauritania;Islamic Republic of Mauritania',
       'Republic of Nicaragua;Republic of Nicaragua',
       'Republic of Belarus;Republic of Belarus', 'Jamaica;Jamaica',
       'Ukraine;Ukraine', 'Republic of Togo;Republic of Togo',
       'Republic of Guatemala;Republic of Guatemala',
       'Republic of Sierra Leone;Republic of Sierra Leone',
       'Republic of Moldova;Republic of Moldova',
       'Republic of Armenia;Republic of Armenia',
       'Republic of Costa Rica;Republic of Costa Rica',
       'Republic of Tajikistan;Republic of Tajikistan',
       'Latin America;Latin America',
       'Federative Republic of Brazil;Federative Republic of Brazil',
       'Bosnia and Herzegovina;Bosnia and Herzegovina',
       'Republic of Suriname;Republic of Suriname', 'Mongolia;Mongolia',
       'Oriental Republic of Uruguay;Oriental Republic of Uruguay',
       'Republic of Kiribati;Republic of Kiribati',
       'Kingdom of Lesotho;Kingdom of Lesotho', 'Tuvalu;Tuvalu',
       'Southern Africa;Southern Africa', 'Georgia;Georgia',
       'Gabonese Republic;Gabonese Republic',
       'Republic of Chile;Republic of Chile',
       'Republic of Kosovo;Republic of Kosovo',
       'Dominican Republic;Dominican Republic',
       'Organization of Eastern Caribbean States;Organization of Eastern Caribbean States',
       'Caribbean;Caribbean', 'Republic of Zimbabwe;Republic of Zimbabwe',
       'Republic of Mauritius;Republic of Mauritius',
       'The Independent State of Papua New Guine;The Independent State of Papua New Guine',
       'Republic of Vanuatu;Republic of Vanuatu',
       'Eastern Africa;Eastern Africa',
       'St. Vincent and the Grenadines;St. Vincent and the Grenadines',
       'Republic of Honduras;Republic of Honduras',
       'Republic of South Sudan;Republic of South Sudan',
       'Republic of Croatia;Republic of Croatia',
       'Democratic Republic of Timor-Leste;Democratic Republic of Timor-Leste',
       'Republic of South Africa;Republic of South Africa',
       'Republic of Botswana;Republic of Botswana',
       'Republic of Kazakhstan;Republic of Kazakhstan',
       'Republic of Azerbaijan;Republic of Azerbaijan',
       'Kingdom of Swaziland;Kingdom of Swaziland',
       'Union of the Comoros;Union of the Comoros',
       'Turkmenistan;Turkmenistan',
       'Europe and Central Asia;Europe and Central Asia',
       'South Asia;South Asia',
       'Macedonia; former Yugoslav Republic of;Macedonia; former Yugoslav Republic of',
       'St. Lucia;St. Lucia', 'Belize;Belize',
       'Republic of Namibia;Republic of Namibia',
       'Republic of the Sudan;Republic of the Sudan',
       'Republic of Paraguay;Republic of Paraguay',
       'Western Balkans;Western Balkans',
       'East Asia and Pacific;East Asia and Pacific',
       'Republic of Bulgaria;Republic of Bulgaria',
       'Central Asia;Central Asia',
       'Republic of Seychelles;Republic of Seychelles',
       'Kingdom of Thailand;Kingdom of Thailand',
       'Republic of Poland;Republic of Poland',
       'Multi-Regional;Multi-Regional',
       'Republic of El Salvador;Republic of El Salvador',
       'Caucasus;Caucasus', 'Russian Federation;Russian Federation',
       'Middle East and North Africa;Middle East and North Africa',
       'Antigua and Barbuda;Antigua and Barbuda',
       'Central America;Central America',
       'Commonwealth of The Bahamas;Commonwealth of The Bahamas',
       'Republic of Trinidad and Tobago;Republic of Trinidad and Tobago',
       "Socialist People's Libyan Arab Jamahiriy;Socialist People's Libyan Arab Jamahiriy",
       'Czech Republic;Czech Republic',
       'Republic of Latvia;Republic of Latvia', 'Mekong;Mekong',
       'American Samoa;American Samoa',
       'Syrian Arab Republic;Syrian Arab Republic', 'Asia;Asia',
       'Andean Countries;Andean Countries', 'Hungary;Hungary',
       'Republic of Equatorial Guinea;Republic of Equatorial Guinea',
       "People's Democratic Republic of Algeria;People's Democratic Republic of Algeria",
       'Barbados;Barbados', 'Malaysia;Malaysia',
       'State of Eritrea;State of Eritrea', 'Mercosur;Mercosur',
       'Slovak Republic;Slovak Republic',
       'Republica Bolivariana de Venezuela;Republica Bolivariana de Venezuela',
       'Islamic Republic of Iran;Islamic Republic of Iran',
       'Republic of Lithuania;Republic of Lithuania',
       'St. Kitts and Nevis;St. Kitts and Nevis',
       'Republic of Korea;Republic of Korea',
       'Republic of Slovenia;Republic of Slovenia',
       'Republic of Estonia;Republic of Estonia',
       'Red Sea and Gulf of Aden;Red Sea and Gulf of Aden',
       'Aral Sea;Aral Sea', 'Republic of Cyprus;Republic of Cyprus',
       'Socialist Federal Republic of Yugoslavia;Socialist Federal Republic of Yugoslavia',
       'Portuguese Republic;Portuguese Republic',
       'Sultanate of Oman;Sultanate of Oman',
       'Hellenic Republic;Hellenic Republic',
       'Kingdom of Spain;Kingdom of Spain', 'Ireland;Ireland',
       'Republic of Singapore;Republic of Singapore',
       'State of Israel;State of Israel',
       'Republic of Finland;Republic of Finland',
       'Republic of Iceland;Republic of Iceland',
       'New Zealand;New Zealand', 'Taiwan; China;Taiwan; China',
       'EU Accession Countries;EU Accession Countries',
       'Sint Maarten;Sint Maarten', 'Japan;Japan',
       'Italian Republic;Italian Republic',
       'Kingdom of Norway;Kingdom of Norway',
       'Republic of Malta;Republic of Malta',
       'Kingdom of Denmark;Kingdom of Denmark',
       'Republic of Austria;Republic of Austria',
       'Commonwealth of Australia;Commonwealth of Australia',
       'Kingdom of Belgium;Kingdom of Belgium',
       'Kingdom of the Netherlands;Kingdom of the Netherlands',
       'Grand Duchy of Luxembourg;Grand Duchy of Luxembourg',
       'French Republic;French Republic'], dtype=object)

# Part 2 - Use the Pycountry library

Did you notice a pattern in the projects data country names? The entries are repeated and separated by a semi-colon like this:
```text
'Kingdom of Spain;Kingdom of Spain'
'New Zealand;New Zealand'
```

The first step is to clean the country name column and get rid of the semi-colon. Do that below:

In [8]:
### 
# TODO: In the df_projects dataframe, create a new column called 'Official Country Name' so that the country name only appears once. 
# For example, `Republic of Malta;Republic of Malta` should be `Republic of Malta`.

# HINT: use the split() method - see https://pandas.pydata.org/pandas-docs/stable/text.html for examples
# HINT: with pandas, you can do all of this with just one line of code
###

df_projects['Official Country Name'] = df_projects['countryname'].str.split(';').str.get(0)

It looks like the projects data set has official country names. Hence, this data set has an entry like "Kingdom of Spain" whereas the indicators data has just "Spain".

Luckily, someone has developed a Python library called [pycountry](https://pypi.org/project/pycountry/). This library has country names, ISO abbreviations, and official country names. While you might not be able to clean all of the data with the help of this Python library, it will probably help. 

Run the code cells below to install the pycountry library and see how it works.

In [9]:
# Run this code cell to install and import the pycountry library
from pycountry import countries

In [10]:
# Run this code cell to see an example of how the library works
countries.get(name='Spain')

Country(alpha_2='ES', alpha_3='ESP', name='Spain', numeric='724', official_name='Kingdom of Spain')

In [11]:
# Run this code cell to see how you can also look up countries without specifying the key
countries.lookup('Kingdom of Spain')

Country(alpha_2='ES', alpha_3='ESP', name='Spain', numeric='724', official_name='Kingdom of Spain')

Using the pycountry library, your task is to clean the projects data so that the country names match the indicators data country names. Iterate through the unique countries in df_projects['Country Name']. Create a dictionary mapping the 'Country Name' to the alpha_3 ISO abbreviations. 

The dictionary should look like:
`{'Kingdom of Spain':'ESP'}`

If a country name cannot be found in the pycountry library, add it to a list called `country_not_found`.

In [18]:
# set up the libraries and variables
from collections import defaultdict
country_not_found = [] # stores countries not found in the pycountry library
project_country_abbrev_dict = defaultdict(str) # set up an empty dictionary of string values

# TODO: iterate through the country names in df_projects. 
# Create a dictionary mapping the country name to the alpha_3 ISO code
for country in df_projects['Official Country Name'].drop_duplicates().sort_values():
    try: 
        # TODO: look up the country name in the pycountry library
        # store the country name as the dictionary key and the ISO-3 code as the value
        project_country_abbrev_dict[country] = countries.lookup(country).alpha_3
    except:
        # If the country name is not in the pycountry library, then print out the country name
        # And store the results in the country_not_found list
        print(country, ' not found')
        country_not_found.append(country)

Africa  not found
Andean Countries  not found
Aral Sea  not found
Asia  not found
Caribbean  not found
Caucasus  not found
Central Africa  not found
Central America  not found
Central Asia  not found
Co-operative Republic of Guyana  not found
Commonwealth of Australia  not found
Democratic Republic of Sao Tome and Prin  not found
Democratic Republic of the Congo  not found
Democratic Socialist Republic of Sri Lan  not found
EU Accession Countries  not found
East Asia and Pacific  not found
Eastern Africa  not found
Europe and Central Asia  not found
Islamic  Republic of Afghanistan  not found
Kingdom of Swaziland  not found
Latin America  not found
Macedonia  not found
Mekong  not found
Mercosur  not found
Middle East and North Africa  not found
Multi-Regional  not found
Organization of Eastern Caribbean States  not found
Oriental Republic of Uruguay  not found
Pacific Islands  not found
Red Sea and Gulf of Aden  not found
Republic of Congo  not found
Republic of Cote d'Ivoire  not found
Republic of Korea  not found
Republic of Kosovo  not found
Republic of Niger  not found
Republic of Rwanda  not found
Republic of Togo  not found
Republic of the Union of Myanmar  not found
Republica Bolivariana de Venezuela  not found
Sint Maarten  not found
Socialist Federal Republic of Yugoslavia  not found
Socialist People's Libyan Arab Jamahiriy  not found
Socialist Republic of Vietnam  not found
Somali Democratic Republic  not found
South Asia  not found
Southern Africa  not found
St. Kitts and Nevis  not found
St. Lucia  not found
St. Vincent and the Grenadines  not found
State of Eritrea  not found
The Independent State of Papua New Guine  not found
West Bank and Gaza  not found
Western Africa  not found
Western Balkans  not found
World  not found

Quite a few country names were not in the pycountry library. Some of these are regions like "South Asia" or "Southern Africa", so it makes sense that these would not show up in the pycountry library.

# Part 3 - Making a Manual Mapping

Perhaps some of these missing df_projects countries are already in the indicators data set. In the next cell, check if any of the countries in the country_not_found list are in the indicator list of countries.

In [19]:
# Run this code cell to 
# iterate through the country_not_found list and check if the country name is in the df_indicator data set
indicator_countries = df_indicator[['Country Name', 'Country Code']].drop_duplicates().sort_values(by='Country Name')

for country in country_not_found:
    if country in indicator_countries['Country Name'].tolist():
        print(country)

South Asia
St. Kitts and Nevis
St. Lucia
St. Vincent and the Grenadines
West Bank and Gaza
World

Unfortunately, there aren't too many country names that match between df_indicator and df_projects. This is where data cleaning becomes especially tedious, but in this case, we've done a lot of the work for you.

We've manually created a dictionary that maps all of the countries in country_not_found to the ISO-3 alpha codes. You **could** try to do this programatically using some sophisticated string matching rules. That might be worth your time for a larger data set. But in this case, it's probably faster to type out the dictionary.

In [20]:
# run this code cell to load the dictionary

country_not_found_mapping = {'Co-operative Republic of Guyana': 'GUY',
             'Commonwealth of Australia':'AUS',
             'Democratic Republic of Sao Tome and Prin':'STP',
             'Democratic Republic of the Congo':'COD',
             'Democratic Socialist Republic of Sri Lan':'LKA',
             'East Asia and Pacific':'EAS',
             'Europe and Central Asia': 'ECS',
             'Islamic  Republic of Afghanistan':'AFG',
             'Latin America':'LCN',
              'Caribbean':'LCN',
             'Macedonia':'MKD',
             'Middle East and North Africa':'MEA',
             'Oriental Republic of Uruguay':'URY',
             'Republic of Congo':'COG',
             "Republic of Cote d'Ivoire":'CIV',
             'Republic of Korea':'KOR',
             'Republic of Niger':'NER',
             'Republic of Kosovo':'XKX',
             'Republic of Rwanda':'RWA',
              'Republic of The Gambia':'GMB',
              'Republic of Togo':'TGO',
              'Republic of the Union of Myanmar':'MMR',
              'Republica Bolivariana de Venezuela':'VEN',
              'Sint Maarten':'SXM',
              "Socialist People's Libyan Arab Jamahiriy":'LBY',
              'Socialist Republic of Vietnam':'VNM',
              'Somali Democratic Republic':'SOM',
              'South Asia':'SAS',
              'St. Kitts and Nevis':'KNA',
              'St. Lucia':'LCA',
              'St. Vincent and the Grenadines':'VCT',
              'State of Eritrea':'ERI',
              'The Independent State of Papua New Guine':'PNG',
              'West Bank and Gaza':'PSE',
              'World':'WLD'}

Next, update the project_country_abbrev_dict variable with these new values.

In [21]:
# TODO: Update the project_country_abbrev_dict with the country_not_found_mapping dictionary
# HINT: This is relatively straightforward. Python dictionaries have a method called update(), which essentially
# appends a dictionary to another dictionary

project_country_abbrev_dict.update(country_not_found_mapping)
project_country_abbrev_dict

defaultdict(str,
            {'American Samoa': 'ASM',
             'Antigua and Barbuda': 'ATG',
             'Arab Republic of Egypt': 'EGY',
             'Argentine Republic': 'ARG',
             'Barbados': 'BRB',
             'Belize': 'BLZ',
             'Bosnia and Herzegovina': 'BIH',
             'Burkina Faso': 'BFA',
             'Central African Republic': 'CAF',
             'Commonwealth of Dominica': 'DMA',
             'Commonwealth of The Bahamas': 'BHS',
             'Czech Republic': 'CZE',
             'Democratic Republic of Timor-Leste': 'TLS',
             'Dominican Republic': 'DOM',
             'Federal Democratic Republic of Ethiopia': 'ETH',
             'Federal Republic of Nigeria': 'NGA',
             'Federated States of Micronesia': 'FSM',
             'Federative Republic of Brazil': 'BRA',
             'French Republic': 'FRA',
             'Gabonese Republic': 'GAB',
             'Georgia': 'GEO',
             'Grand Duchy of Luxembourg': 'LUX',
             'Grenada': 'GRD',
             'Hashemite Kingdom of Jordan': 'JOR',
             'Hellenic Republic': 'GRC',
             'Hungary': 'HUN',
             'Ireland': 'IRL',
             'Islamic Republic of Iran': 'IRN',
             'Islamic Republic of Mauritania': 'MRT',
             'Islamic Republic of Pakistan': 'PAK',
             'Italian Republic': 'ITA',
             'Jamaica': 'JAM',
             'Japan': 'JPN',
             'Kingdom of Belgium': 'BEL',
             'Kingdom of Bhutan': 'BTN',
             'Kingdom of Cambodia': 'KHM',
             'Kingdom of Denmark': 'DNK',
             'Kingdom of Lesotho': 'LSO',
             'Kingdom of Morocco': 'MAR',
             'Kingdom of Norway': 'NOR',
             'Kingdom of Spain': 'ESP',
             'Kingdom of Thailand': 'THA',
             'Kingdom of Tonga': 'TON',
             'Kingdom of the Netherlands': 'NLD',
             'Kyrgyz Republic': 'KGZ',
             "Lao People's Democratic Republic": 'LAO',
             'Lebanese Republic': 'LBN',
             'Malaysia': 'MYS',
             'Mongolia': 'MNG',
             'Montenegro': 'MNE',
             'Nepal': 'NPL',
             'New Zealand': 'NZL',
             "People's Democratic Republic of Algeria": 'DZA',
             "People's Republic of Bangladesh": 'BGD',
             "People's Republic of China": 'CHN',
             'Plurinational State of Bolivia': 'BOL',
             'Portuguese Republic': 'PRT',
             'Republic of Albania': 'ALB',
             'Republic of Angola': 'AGO',
             'Republic of Armenia': 'ARM',
             'Republic of Austria': 'AUT',
             'Republic of Azerbaijan': 'AZE',
             'Republic of Belarus': 'BLR',
             'Republic of Benin': 'BEN',
             'Republic of Botswana': 'BWA',
             'Republic of Bulgaria': 'BGR',
             'Republic of Burundi': 'BDI',
             'Republic of Cabo Verde': 'CPV',
             'Republic of Cameroon': 'CMR',
             'Republic of Chad': 'TCD',
             'Republic of Chile': 'CHL',
             'Republic of Colombia': 'COL',
             'Republic of Costa Rica': 'CRI',
             'Republic of Croatia': 'HRV',
             'Republic of Cyprus': 'CYP',
             'Republic of Djibouti': 'DJI',
             'Republic of Ecuador': 'ECU',
             'Republic of El Salvador': 'SLV',
             'Republic of Equatorial Guinea': 'GNQ',
             'Republic of Estonia': 'EST',
             'Republic of Fiji': 'FJI',
             'Republic of Finland': 'FIN',
             'Republic of Ghana': 'GHA',
             'Republic of Guatemala': 'GTM',
             'Republic of Guinea': 'GIN',
             'Republic of Guinea-Bissau': 'GNB',
             'Republic of Haiti': 'HTI',
             'Republic of Honduras': 'HND',
             'Republic of Iceland': 'ISL',
             'Republic of India': 'IND',
             'Republic of Indonesia': 'IDN',
             'Republic of Iraq': 'IRQ',
             'Republic of Kazakhstan': 'KAZ',
             'Republic of Kenya': 'KEN',
             'Republic of Kiribati': 'KIR',
             'Republic of Latvia': 'LVA',
             'Republic of Liberia': 'LBR',
             'Republic of Lithuania': 'LTU',
             'Republic of Madagascar': 'MDG',
             'Republic of Malawi': 'MWI',
             'Republic of Maldives': 'MDV',
             'Republic of Mali': 'MLI',
             'Republic of Malta': 'MLT',
             'Republic of Mauritius': 'MUS',
             'Republic of Moldova': 'MDA',
             'Republic of Mozambique': 'MOZ',
             'Republic of Namibia': 'NAM',
             'Republic of Nicaragua': 'NIC',
             'Republic of Palau': 'PLW',
             'Republic of Panama': 'PAN',
             'Republic of Paraguay': 'PRY',
             'Republic of Peru': 'PER',
             'Republic of Poland': 'POL',
             'Republic of Senegal': 'SEN',
             'Republic of Serbia': 'SRB',
             'Republic of Seychelles': 'SYC',
             'Republic of Sierra Leone': 'SLE',
             'Republic of Singapore': 'SGP',
             'Republic of Slovenia': 'SVN',
             'Republic of South Africa': 'ZAF',
             'Republic of South Sudan': 'SSD',
             'Republic of Suriname': 'SUR',
             'Republic of Tajikistan': 'TJK',
             'Republic of The Gambia': 'GMB',
             'Republic of Trinidad and Tobago': 'TTO',
             'Republic of Tunisia': 'TUN',
             'Republic of Turkey': 'TUR',
             'Republic of Uganda': 'UGA',
             'Republic of Uzbekistan': 'UZB',
             'Republic of Vanuatu': 'VUT',
             'Republic of Yemen': 'YEM',
             'Republic of Zambia': 'ZMB',
             'Republic of Zimbabwe': 'ZWE',
             'Republic of the Marshall Islands': 'MHL',
             'Republic of the Philippines': 'PHL',
             'Republic of the Sudan': 'SDN',
             'Romania': 'ROU',
             'Russian Federation': 'RUS',
             'Samoa': 'WSM',
             'Slovak Republic': 'SVK',
             'Solomon Islands': 'SLB',
             'State of Israel': 'ISR',
             'Sultanate of Oman': 'OMN',
             'Syrian Arab Republic': 'SYR',
             'Taiwan': 'TWN',
             'Turkmenistan': 'TKM',
             'Tuvalu': 'TUV',
             'Ukraine': 'UKR',
             'Union of the Comoros': 'COM',
             'United Mexican States': 'MEX',
             'United Republic of Tanzania': 'TZA',
             'Co-operative Republic of Guyana': 'GUY',
             'Commonwealth of Australia': 'AUS',
             'Democratic Republic of Sao Tome and Prin': 'STP',
             'Democratic Republic of the Congo': 'COD',
             'Democratic Socialist Republic of Sri Lan': 'LKA',
             'East Asia and Pacific': 'EAS',
             'Europe and Central Asia': 'ECS',
             'Islamic  Republic of Afghanistan': 'AFG',
             'Latin America': 'LCN',
             'Caribbean': 'LCN',
             'Macedonia': 'MKD',
             'Middle East and North Africa': 'MEA',
             'Oriental Republic of Uruguay': 'URY',
             'Republic of Congo': 'COG',
             "Republic of Cote d'Ivoire": 'CIV',
             'Republic of Korea': 'KOR',
             'Republic of Niger': 'NER',
             'Republic of Kosovo': 'XKX',
             'Republic of Rwanda': 'RWA',
             'Republic of Togo': 'TGO',
             'Republic of the Union of Myanmar': 'MMR',
             'Republica Bolivariana de Venezuela': 'VEN',
             'Sint Maarten': 'SXM',
             "Socialist People's Libyan Arab Jamahiriy": 'LBY',
             'Socialist Republic of Vietnam': 'VNM',
             'Somali Democratic Republic': 'SOM',
             'South Asia': 'SAS',
             'St. Kitts and Nevis': 'KNA',
             'St. Lucia': 'LCA',
             'St. Vincent and the Grenadines': 'VCT',
             'State of Eritrea': 'ERI',
             'The Independent State of Papua New Guine': 'PNG',
             'West Bank and Gaza': 'PSE',
             'World': 'WLD'})

# Part 5 - Make a 'Country Code' Column

Next, create a 'Country Code' column in the data_projects data frame. Use the project_country_abbrev_dict and df_projects['Country Name'] column to create a new columns called 'Country 'Code'.

In [38]:
# TODO: Use the project_country_abbrev_dict and the df_projects['Country Name'] column to make a new column
# of the alpha-3 country codes. This new column should be called 'Country Code'.

# HINT: Use the apply method and a lambda function
# https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.apply.html

df_projects['Country Code'] = df_projects['Official Country Name'].apply(lambda x: project_country_abbrev_dict[x])

In [35]:
# Run this code cell to see which projects in the df_projects data frame still have no country code abbreviation.
# In other words, these projects do not have a matching population value in the df_indicator data frame.
df_projects[df_projects['Country Code'] == '']

,id,regionname,countryname,prodline,lendinginstr,lendinginstrtype,envassesmentcategorycode,supplementprojectflg,productlinetype,projectstatusdisplay,...,mjtheme4name,mjtheme5name,location,GeoLocID,GeoLocName,Latitude,Longitude,Country,Official Country Name,Country Code
31,P166648,Africa,Central Africa;Central Africa,RE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Central Africa,
39,P163752,Africa,Africa;Africa,PE,Investment Project Financing,IN,A,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Africa,
58,P164728,Africa,Africa;Africa,PE,Investment Project Financing,IN,NaN,Y,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Africa,
69,P161329,Africa,Western Africa;Western Africa,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Western Africa,
103,P164468,East Asia and Pacific,Pacific Islands;Pacific Islands,PE,Investment Project Financing,IN,NaN,Y,L,Active,...,NaN,NaN,0002134431!$!Republic of Vanuatu!$!-16!$!167!$...,0002134431;0002135171,Republic of Vanuatu;Port-Vila,-16;-17.73381,167;168.32188,VU;VU,Pacific Islands,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17963,P009136,Europe and Central Asia,Socialist Federal Republic of Yugoslavia;Socia...,PE,Specific Investment Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Socialist Federal Republic of Yugoslavia,
18134,P000620,Africa,Africa;Africa,PE,Specific Investment Loan,IN,C,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Africa,
18175,P009135,Europe and Central Asia,Socialist Federal Republic of Yugoslavia;Socia...,PE,Structural Adjustment Loan,AD,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Socialist Federal Republic of Yugoslavia,
18197,P009134,Europe and Central Asia,Socialist Federal Republic of Yugoslavia;Socia...,PE,Structural Adjustment Loan,AD,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Socialist Federal Republic of Yugoslavia,
18228,P009133,Europe and Central Asia,Socialist Federal Republic of Yugoslavia;Socia...,PE,Specific Investment Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Socialist Federal Republic of Yugoslavia,

You'll notice that there are still a few entries without country abbreviations. This includes projects that were labeled as "Africa" rather than a specific country. It also includes "Yugoslavia", which is a country that ceased to exist in the 1990s.

# Conclusion

Now the df_projects dataframe and the df_indicator dataframe have a matching column called 'Country Code'. But these two data frames can't be merged quite yet. 

Each project in the df_projects dataframe also has a date associated with it. The idea would be to merge the df_projects dataframe with the df_indicator dataframe so that each project also had a population value associated with it. There are still more data transformations to do in order for that to be possible. 

In fact, the **challenge** problem from the previous exercise on merging data would help quite a bit. In that exercise, the indicator data was transformed from a [wide format to a long format](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.melt.html).

You could then merge the df_projects dataframe and the df_indicator dataframe using the alpha-3 country abbreviation and the project or indicator year. You can start to see how data transformations become a series of processes that pipeline data from one format into a different format.